### ISSUE TITLE
Some supported ores broken

### ISSUE THREAD

**Issue by Pinsive** [SuperMartijn642/OreGrowth#10]
Minecraft version: 1.19.2
Mod version: 1.0.8 Forge, downloaded from modrinth (if that could make any difference)

As the screenshots show, some of the ores in my game will not generate ore growths naturally and will not allow me to place ore growths on them, even using commands. If I attempt to place one with commands, a floating iron ore growth will appear.

![image](https://github.com/SuperMartijn642/OreGrowth/assets/151463178/98968341-a276-4cce-9d4f-68a5575c13c7)
![image](https://github.com/SuperMartijn642/OreGrowth/assets/151463178/f58029fa-23f3-48af-aae8-db4f7e9ca7fb)

This includes some ores from supported mods: the thermal series ores and yellorite ore from extreme reactors (though angelsite and benitoite can generate ore growths as they should). The other two broken ores are the skyjade ore, from deep aether, and pigsteel, from the pigsteel mod, but I understand that your mod doesn't support these.

I have to imagine it's an issue with the order that mods are loaded? but that wouldn't explain the yellorite issue. I don't know very much about programming, so I don't know what else I would need to tell you to help work this out. For now, I think I can 'fix' it myself using crafttweaker, but please look into this!

Other (potentially) relevant mods:
Deep Aether 1.0.3 by TeamRazorDevs
Extreme Reactors 2.0.71 by ZeronoRyouki
Pigsteel 4.0.0 by uraneptus
Thermal Dynamics 10.3.0
Thermal Expansion 10.3.1
Thermal Foundation 10.3.1
Thermal Innovation 10.3.0
Thermal Integration 10.3.0

**Comment by Pinsive** [comment]
Thought I should add:
![image](https://github.com/SuperMartijn642/OreGrowth/assets/151463178/abed15c6-e016-44cc-81f6-70bcea8becc9)
![image](https://github.com/SuperMartijn642/OreGrowth/assets/151463178/455085a2-7a9a-4849-aea4-8bc2d2701067)

The broken ores are not showing their ore growth recipes in JEI. 

Thanks

**Comment by SuperMartijn642** [comment]
Could you share the `latest.log` file?
Likely what happened is that I misspelled some of the names for the ores (although everything from Thermal Foundation missing is a bit odd) and thus it will print an error in the log for the recipes as it can't find the items or blocks.

**Comment by SuperMartijn642** [comment]
Seems I had `yellorite_nugget` as the output for the yellorite ore recipes, while it should be `yellorium_nugget`.
For Thermal Foundation I had the wrong modid. All the thermal series mods just use `thermal` whilst I had `thermalfoundation`.

Both have been fixed now in Ore Growth version 1.0.9.
I also added recipes for Deep Aether and Pigsteel.
Thank you for reporting the issue!

**Comment by Pinsive** [comment]
Thanks so much!

**Comment by Pinsive** [comment]
Sorry to keep pestering you about this, but you forgot cinnabar! After loading up the game, I noticed cinnabar still wasn't generating ore growths. I managed to open up the mod in 7zip and there didn't seem to be any recipe json files for cinnabar.

Thanks again

**Comment by SuperMartijn642** [comment]
From which mod would that be?

**Comment by Pinsive** [comment]
Sorry, it's one of the thermal ores

**Comment by SuperMartijn642** [comment]
Ah it seems cinnabar ore is not listed in the creative tab nor in JEI.
I added a recipe for it now in Ore Growth version 1.0.10.
